pipeline {
    agent any
       stages {

        stage('ssh into remote') {   
                        steps {
                                withCredentials([usernamePassword(credentialsId: 'uat-to-dss', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                                sh'''
                                        sshpass -p $PASSWORD ssh -o "StrictHostKeyChecking=no" $USERNAME@10.0.22.2 bash devops-config/uat-env/accountmanagement-service.sh
                                '''
                                }
                        }
                }
    }
}
