pipeline {
    environment{
        BUILD_TRIGGER_BY = "${currentBuild.getBuildCauses()[0].shortDescription}"
    }
    agent {
        node {
            label 'DSS'
	    customWorkspace '/home/paywalletdevops/new_paywallet_backend_services/new-payroll-provider-service'
        }
    }
	parameters {
		string(name: 'Branch', defaultValue: 'temp-develop', description: 'Enter the branch to deploy?')
	}
    stages {
        stage('Code checkout') {
            steps {
                git branch: '$Branch', credentialsId: 'Github-Key', url: 'https://github.com/Maveric-Digital/new-payroll-provider-service.git'
            }
        }
	stage ('Maven Build for new-payroll-provider-service') {
            steps {
                sh """
                mvn clean install -DskipTests
                """
            }
        }
	stage ('Sonarqube') {
            steps {
                sh """
		    mvn sonar:sonar \
			-Dsonar.projectKey=PayWallet-new_Payroll_Provider-API \
			-Dsonar.host.url=https://sonar-dev.paywalletllc.com  \
			-Dsonar.login=728afe36c480dde2a68108b5fa731832bcd18bed \
			-Dsonar.projectName=Dev-new-payroll-provider-service
                """
            }
        }
	stage ('Remove the docker container and images') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh """
			sudo docker rm -f new-payroll-provider-service_container
			sudo docker rmi new-payroll-provider-service
                    """
                }
            }
        }
	stage ('Run Docker-compose') {
            steps {
                sh """
                    sudo docker-compose -f docker-compose.yml up -d
                """
            }
        }
    }
    post {
        success {
                slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}) ${BUILD_TRIGGER_BY}")
        }       
        failure {
                slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}) ${BUILD_TRIGGER_BY}")
        }       
    }
}
