pipeline {
    agent any 
       stages {
           
        stage('devops-config repo sync') {   
                steps {
                    withCredentials([usernamePassword(credentialsId: 'dev-vm', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh'''
                        sshpass -p $PASSWORD ssh -o "StrictHostKeyChecking=no" $USERNAME@10.0.2.3 bash devops-config.sh
                    '''
                                }
                        }
                }

        stage('Build and Deploy') {   
                steps {
                    withCredentials([usernamePassword(credentialsId: 'dev-vm', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh'''
                        sshpass -p $PASSWORD ssh -o "StrictHostKeyChecking=no" $USERNAME@10.0.2.3 bash devops-config/Dev-env/luther-sales-borrower-app.sh
                    '''
                                }
                        }
                }
    }
      post {
        always {
            cleanWs()
        }
    }
}
