pipeline {
    environment{
	BUILD_TRIGGER_BY = "${currentBuild.getBuildCauses()[0].shortDescription}"
    }
    agent {
        node {
            label 'DSS-FE'
	    customWorkspace '/home/paywalletdevops/Prod_frontend-services/luthersales-inhouse-app-php-code'
        }
    }
	parameters {
		string(name: 'Branch', defaultValue: 'temp-production', description: 'Enter the branch to deploy?')
	}
    stages {
        stage('Code checkout') {
            steps {
                git branch: '$Branch', credentialsId: 'Github-Key', url: 'https://github.com/Maveric-Digital/luthersales-inhouse-app-php-code.git'
            }
        }
	stage ('Remove the docker container and images') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh """
			sudo docker rm -f luthersales-inhouse-app-php-code_container
			sudo docker rmi luthersales-inhouse-app-php-code
                    """
                }
            }
        }
	stage ('Run Docker-compose') {
            steps {
                sh """
                    sudo docker-compose -f docker-compose.yml up -d
                """
            }
        }
    }
    post {
	success {
		slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}) ${BUILD_TRIGGER_BY}")
	}
	failure {
		slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}) ${BUILD_TRIGGER_BY}")
	}
    }
}
