pipeline {
    agent any 
       stages {

        stage('ssh into remote') {   
			steps {
				withCredentials([usernamePassword(credentialsId: 'dev-vm', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
				sh'''
					sshpass -p $PASSWORD ssh -o "StrictHostKeyChecking=no" $USERNAME@10.0.2.3 bash devops-config/Dev-env/luthersales-inhouse-app-php-code.sh
				'''
				}
			}
		}
    }

        post {
        always {
            cleanWs()
        }
    } 
}
