pipeline {
    agent any 
       stages {

        stage('ssh into remote') {   
                        steps {
                                withCredentials([usernamePassword(credentialsId: 'dev-vm', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                                sh'''
                                        sshpass -p $PASSWORD ssh $USERNAME@10.0.2.3 bash devops-config.sh
                                        bash devops-config/Dev-env/accountmanagement-service.sh
                                '''
                                }
                        }
                }
    }
}
