pipeline {
    agent any 
       stages {

        stage('Deployting otp-service') {   
			steps {
				withCredentials([usernamePassword(credentialsId: 'dev-vm', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
				sh'''
					sshpass -p $PASSWORD ssh -o "StrictHostKeyChecking=no" $USERNAME@10.0.2.3 bash devops-config/Dev-env/otp-service.sh
				'''
				}
			}
		}
    }
	
	 post {
        always {
            cleanWs()
        }
    } 
}
