pipeline {
    environment{
        BUILD_TRIGGER_BY = "${currentBuild.getBuildCauses()[0].shortDescription}"
    }
    agent {
        node {
            label 'DSS'
	    customWorkspace '/home/paywalletdevops/new_paywallet_backend_services/payroll-provider-service'
        }
    }
	parameters {
		string(name: 'Branch', defaultValue: 'temp-develop', description: 'Enter the branch to deploy?')
	}
    stages {
        stage('Code checkout') {
            steps {
                git branch: '$Branch', credentialsId: 'Github-Key', url: 'https://github.com/Maveric-Digital/payroll-provider-service.git'
		sh'''
			sed -i 's/dev/uat/g' Dockerfile
		'''
            }
        }
	stage ('Maven Build for payroll-provider-service') {
            steps {
                sh """
                mvn clean install -DskipTests
                """
            }
        }
	stage ('Sonarqube') {
            steps {
                sh """
		    mvn sonar:sonar \
			-Dsonar.projectKey=PayWallet-UAT-Payroll_Provider-API \
			-Dsonar.host.url=http://sonar-dev.paywalletllc.com:9000 \
			-Dsonar.login=045d3e4a4208f9109f557cb28415b24bad272f99 \
			-Dsonar.projectName=UAT-payroll-provider-service
                """
            }
        }
	stage ('Remove the docker container and images') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh """
			sudo docker rm -f payroll-provider-service_container
			sudo docker rmi payroll-provider-service
                    """
                }
            }
        }
	stage ('Run Docker-compose') {
            steps {
                sh """
                    sudo docker-compose -f docker-compose.yml up -d
                """
            }
        }
    }
    post {
        success {
                slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}) ${BUILD_TRIGGER_BY}")
        }       
        failure {
                slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL}) ${BUILD_TRIGGER_BY}")
        }       
    }
}
